// <auto-generated />
using EntangoApi;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace EntangoApi.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251103132432_AddPriceList")]
    partial class AddPriceList
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("EntangoApi.Models.PriceList", b =>
                {
                    b.Property<int>("PriceListId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("PriceListId"));

                    b.Property<string>("PriceListAuthor")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("PriceListDescription")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("PriceListVersion")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<decimal>("ProductBusinessProfitPerc")
                        .HasColumnType("decimal(5,2)");

                    b.Property<string>("ProductDescription")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<decimal>("ProductEquipmentPerc")
                        .HasColumnType("decimal(5,2)");

                    b.Property<string>("ProductExtendedDescription")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<decimal>("ProductGeneralExpensePerc")
                        .HasColumnType("decimal(5,2)");

                    b.Property<decimal>("ProductHirePerc")
                        .HasColumnType("decimal(5,2)");

                    b.Property<string>("ProductId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<decimal>("ProductLabourPerc")
                        .HasColumnType("decimal(5,2)");

                    b.Property<decimal>("ProductMaterialPerc")
                        .HasColumnType("decimal(5,2)");

                    b.Property<decimal>("ProductNetPrice")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("ProductPrice")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("ProductSafetyPerc")
                        .HasColumnType("decimal(5,2)");

                    b.Property<string>("ProductUM")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("ProductClassification")
                         .HasMaxLength(100)
                         .HasColumnType("character varying(100)");

                    b.HasKey("PriceListId");

                    b.ToTable("PriceLists");
                });
#pragma warning restore 612, 618
        }
    }
}
